### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by ne0deam** [itmo-infocom/calc_examples#1]
`./calc
2 * 5
expr: syntax error: unexpected argument ‘Ma’`

**Comment by sadov** [comment]
Yes, of course, if you're talking about Example_2 - this is just a sample troubleshooting from my UNIX and Linux lectures:
https://youtu.be/_RBt_aULTh0?list=PLHlIuA7HfUlrjNq2yN_vabMj8V_H2gCeY&t=202 
This is fixed in Example_3:
https://www.youtube.com/watch?v=EWH8faqRVOw&list=PLHlIuA7HfUlrjNq2yN_vabMj8V_H2gCeY&index=52
